services:
  - type: web
    name: djadwal
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start:api
    envVars:
      - key: NODE_OPTIONS
        value: "--max_old_space_size=4096"
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
