services:
  - type: web
    name: djadwal
    env: node
    plan: free
    buildCommand: pnpm install && pnpm --filter @djadwal/web build --logLevel info
    startCommand: pnpm run start:api
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
